package Entity;
// Generated Oct 20, 2016 11:06:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PenjualanMaster generated by hbm2java
 */
public class PenjualanMaster  implements java.io.Serializable {


     private String noTransaksi;
     private Date tanggal;
     private Double total;
     private Set penjualanDetils = new HashSet(0);

    public PenjualanMaster() {
    }

	
    public PenjualanMaster(String noTransaksi) {
        this.noTransaksi = noTransaksi;
    }
    public PenjualanMaster(String noTransaksi, Date tanggal, Double total, Set penjualanDetils) {
       this.noTransaksi = noTransaksi;
       this.tanggal = tanggal;
       this.total = total;
       this.penjualanDetils = penjualanDetils;
    }
   
    public String getNoTransaksi() {
        return this.noTransaksi;
    }
    
    public void setNoTransaksi(String noTransaksi) {
        this.noTransaksi = noTransaksi;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set getPenjualanDetils() {
        return this.penjualanDetils;
    }
    
    public void setPenjualanDetils(Set penjualanDetils) {
        this.penjualanDetils = penjualanDetils;
    }




}


