package pos.util;
// Generated Oct 20, 2016 11:06:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Barang generated by hbm2java
 */
public class Barang  implements java.io.Serializable {


     private String kodeBarang;
     private String namaBarang;
     private Double harga;
     private String satuan;
     private Integer stok;
     private Set penjualanDetils = new HashSet(0);

    public Barang() {
    }

	
    public Barang(String kodeBarang) {
        this.kodeBarang = kodeBarang;
    }
    public Barang(String kodeBarang, String namaBarang, Double harga, String satuan, Integer stok, Set penjualanDetils) {
       this.kodeBarang = kodeBarang;
       this.namaBarang = namaBarang;
       this.harga = harga;
       this.satuan = satuan;
       this.stok = stok;
       this.penjualanDetils = penjualanDetils;
    }
   
    public String getKodeBarang() {
        return this.kodeBarang;
    }
    
    public void setKodeBarang(String kodeBarang) {
        this.kodeBarang = kodeBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public Double getHarga() {
        return this.harga;
    }
    
    public void setHarga(Double harga) {
        this.harga = harga;
    }
    public String getSatuan() {
        return this.satuan;
    }
    
    public void setSatuan(String satuan) {
        this.satuan = satuan;
    }
    public Integer getStok() {
        return this.stok;
    }
    
    public void setStok(Integer stok) {
        this.stok = stok;
    }
    public Set getPenjualanDetils() {
        return this.penjualanDetils;
    }
    
    public void setPenjualanDetils(Set penjualanDetils) {
        this.penjualanDetils = penjualanDetils;
    }




}


