package pos.util;
// Generated Oct 20, 2016 11:06:39 AM by Hibernate Tools 4.3.1



/**
 * PenjualanDetil generated by hbm2java
 */
public class PenjualanDetil  implements java.io.Serializable {


     private Integer id;
     private Barang barang;
     private PenjualanMaster penjualanMaster;
     private Integer jumlah;
     private Double subTotal;

    public PenjualanDetil() {
    }

    public PenjualanDetil(Barang barang, PenjualanMaster penjualanMaster, Integer jumlah, Double subTotal) {
       this.barang = barang;
       this.penjualanMaster = penjualanMaster;
       this.jumlah = jumlah;
       this.subTotal = subTotal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Barang getBarang() {
        return this.barang;
    }
    
    public void setBarang(Barang barang) {
        this.barang = barang;
    }
    public PenjualanMaster getPenjualanMaster() {
        return this.penjualanMaster;
    }
    
    public void setPenjualanMaster(PenjualanMaster penjualanMaster) {
        this.penjualanMaster = penjualanMaster;
    }
    public Integer getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(Integer jumlah) {
        this.jumlah = jumlah;
    }
    public Double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(Double subTotal) {
        this.subTotal = subTotal;
    }




}


